name: Test

on: [push, pull_request]

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.10"] # min and max supported versions?
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgirepository1.0-dev gettext python3-gi gobject-introspection \
          gir1.2-gtk-3.0 gir1.2-gtksource-4 libgtksourceview-4-0 libgtksourceview-4-dev
        python -m pip install --upgrade pip
        pip install wheel setuptools psutil
        pip install .
    - name: Run tests
      run: |
        mkdir -p /tmp/input-remapper-runner
        sudo chmod -R 0777 /tmp #FIXME permissions error accessing file in /tmp https://gist.github.com/LunNova/2889052e9e46b90ae0a0b32d8599934d
        mkdir -p test_tmp
        TMPDIR="$(realpath test_tmp)" sudo python tests/test.py unit
